-- CONSULTAS --
-- Votos de cada candidato:
SELECT
  CAND.NOMEPOPULAR,
  CAND.NUMERO,
  COUNT(1)
FROM
  VOTO
INNER JOIN CANDIDATO CAND
ON
  CAND.IDCANDIDATO = VOTO.IDCANDIDATO
GROUP BY
  VOTO.IDCANDIDATO;